### ISSUE TITLE
[Kotlin v2] CONST_VAL_WITHOUT_INITIALIZER warnings

### ISSUE THREAD

**Issue by AlexanderEggers** [yshrsmz/BuildKonfig#148]
**Describe the bug**
When running a recent RC of the upcoming Kotlin v2 version (2.0.0-RC2), I'm running into a bunch of `CONST_VAL_WITHOUT_INITIALIZER` warnings:

> This code uses error suppression for 'CONST_VAL_WITHOUT_INITIALIZER'. While it might compile and work, the compiler behavior is UNSPECIFIED and WON'T BE PRESERVED. Please report your use case to the Kotlin issue tracker instead: https://kotl.in/issue

This PR seems to be related to this issue: https://github.com/yshrsmz/BuildKonfig/pull/70.

**To Reproduce**
Run a project using a recent Kotlin v2 RC. Add buildKonfig to the project, set a few props to const and observe the build throwing a lot of warnings during any build.

**Expected behavior**
No warnings.

**Desktop (please complete the following information):**
 - OS: Mac OS 14.4.1
 - BuildKonfig Version: v0.15.1
 - Kotlin Version: 2.0.0-RC2
 - Gradle Version: 8.6

**Comment by Mina-1316** [comment]
Isn't `expect val` and `actual const val` isn't fit on this case? 
as the reference: https://youtrack.jetbrains.com/issue/KT-18856/Can-we-have-expect-actual-consts#focus=Comments-27-2335514.0-0

We need to investigate how the compiler handles it internally and what errors may occur when `expect` and multiple `actual`s are `const` mixed declarations, but it seems to be built well for now...

**Comment by yshrsmz** [comment]
I'm closing this for now. Feel free to comment if you still see the issue.

> Isn't `expect val` and `actual const val` isn't fit on this case?

Regarding this, please open a new issue if you need this implemented.

**Comment by RockLobster** [comment]
This seems to have become a compilation error, can we reopen?

```
> Task :shared:compileCommonMainKotlinMetadata FAILED
e: org.jetbrains.kotlin.util.SourceCodeAnalysisException: java.lang.IllegalArgumentException: Const property has no const initializer expression. Got @R|kotlin/Suppress|(names = vararg(String(CONST_VAL_WITHOUT_INITIALIZER))) public final expect const val VERSION_NAME: R|kotlin/String|
    public get(): R|kotlin/String|

        at org.jetbrains.kotlin.util.AnalysisExceptionsKt.wrapIntoSourceCodeAnalysisExceptionIfNeeded(AnalysisExceptions.kt:28)
        at org.jetbrains.kotlin.fir.FirCliExceptionHandler.handleExceptionOnElementAnalysis(Utils.kt:266)
        at org.jetbrains.kotlin.fir.serialization.FirElementSerializer.propertyProto(FirElementSerializer.kt:1801)
        at org.jetbrains.kotlin.fir.serialization.FirElementSerializer.classProtoImpl(FirElementSerializer.kt:258)
        at org.jetbrains.kotlin.fir.serialization.FirElementSerializer.classProto(FirElementSerializer.kt:169)
        at org.jetbrains.kotlin.fir.serialization.FirKlibSerializationKt.serializeSingleFirFile$makeClassProtoWithNested(firKlibSerialization.kt:56)
        at org.jetbrains.kotlin.fir.serialization.FirKlibSerializationKt.serializeSingleFirFile(firKlibSerialization.kt:64)
        at org.jetbrains.kotlin.fir.serialization.FirKlibSerializationKt.serializeSingleFirFile$default(firKlibSerialization.kt:24)
        at org.jetbrains.kotlin.cli.pipeline.metadata.MetadataKlibInMemorySerializerPhase.executePhase(MetadataKlibSerializerPhase.kt:43)
        at org.jetbrains.kotlin.cli.pipeline.metadata.MetadataKlibInMemorySerializerPhase.executePhase(MetadataKlibSerializerPhase.kt:27)
        at org.jetbrains.kotlin.cli.pipeline.PipelinePhase.phaseBody(PipelinePhase.kt:68)
        at org.jetbrains.kotlin.cli.pipeline.PipelinePhase.phaseBody(PipelinePhase.kt:58)
        at org.jetbrains.kotlin.config.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:102)
        at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:22)
        at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:22)
        at org.jetbrains.kotlin.config.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:53)
        at org.jetbrains.kotlin.cli.pipeline.AbstractCliPipeline.runPhasedPipeline(AbstractCliPipeline.kt:109)
        at org.jetbrains.kotlin.cli.pipeline.AbstractCliPipeline.execute(AbstractCliPipeline.kt:68)
        at org.jetbrains.kotlin.cli.metadata.KotlinMetadataCompiler.doExecutePhased(KotlinMetadataCompiler.kt:61)
        at org.jetbrains.kotlin.cli.metadata.KotlinMetadataCompiler.doExecutePhased(KotlinMetadataCompiler.kt:54)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:91)
        at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.kt:363)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1898)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:905)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:598)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:844)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:721)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:720)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalArgumentException: Const property has no const initializer expression. Got @R|kotlin/Suppress|(names = vararg(String(CONST_VAL_WITHOUT_INITIALIZER))) public final expect const val VERSION_NAME: R|kotlin/String|
    public get(): R|kotlin/String|

        at org.jetbrains.kotlin.fir.serialization.FirSerializerExtensionBase.absentInitializerGuard(FirSerializerExtensionBase.kt:130)
        at org.jetbrains.kotlin.fir.serialization.FirSerializerExtensionBase.serializeProperty(FirSerializerExtensionBase.kt:124)
        at org.jetbrains.kotlin.fir.serialization.FirKLibSerializerExtension.serializeProperty(FirKLibSerializerExtension.kt:70)
        at org.jetbrains.kotlin.fir.serialization.FirElementSerializer.propertyProto(FirElementSerializer.kt:654)
        ... 36 more
```

**Comment by yshrsmz** [comment]
@RockLobster can you create a new issue?

**Comment by yshrsmz** [comment]
This has been reported as a compilation error with Kotlin 2.3+ (K2 compiler). Tracking in #277.

K2 no longer allows `expect const val` without an initializer, and `@Suppress("CONST_VAL_WITHOUT_INITIALIZER")` no longer works. The fix is to stop generating `expect const val` entirely and instead generate `expect val` + `actual const val`.
